### ISSUE TITLE
Generate theme path error on Windows

### ISSUE THREAD

**Issue by pooooriya** [emeks-studio/antd-custom-theme-generator#7]
$ generate-theme './styles/custom-theme.less' './styles/custom-theme.css'
Error: Command failed: node_modules/less/bin/lessc --js /tmp/generated-theme.less C:\Users\Administrator\Desktop\test\rtimer\'.\styles\custom-theme.css'
'node_modules' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: "node_modules/less/bin/lessc --js /tmp/generated-theme.less C:\\Users\\Administrator\\Desktop\\test\\rtimer\\'.\\styles\\custom-theme.css'"
}

cant use generate theme command

**Comment by pooooriya** [comment]
its only work on linux and mac and not working on windows !!!!!

**Comment by singhtamanpreet** [comment]
I am getting the same error and I am using ubuntu. I wonder what is the reason. 
The program is not able to find generate theme

**Comment by singhtamanpreet** [comment]
@pooooriya 
Follow these steps:

- Create a generate-theme.less file at the root of the app.
- Run the following command

`npx @emeks/antd-custom-theme-generator generate-theme`

You will get output in a file named custom-theme.css

**Comment by singhtamanpreet** [comment]
I am not able to generate dark mode with this command

`npx @emeks/antd-custom-theme-generator generate-theme`

Kindly provide an example to do so. Thanks in advance

**Comment by randomeduc** [comment]
Hey thanks for report the issue

@pooooriya we will check that and try to figure out what happen with Windows paths, stay tune.

@singhtamanpreet I check that the doc is wrong because the `generate-theme` arg is no longer needed. For example if you want to run dark theme you need this command `npx @emeks/antd-custom-theme-generator ./custom-theme.less ./custom-theme.css ./node_modules/antd dark`. We will fix that too and add some examples, thanks!

**Comment by mk-emeks** [comment]
@pooooriya new release [v0.2.0](https://github.com/emeks-studio/antd-custom-theme-generator/releases/tag/v0.2.0) in case you want to give it a try!
